# Site settings
title: Blockstream - Crypto Feed
description: "Cryptocurrency data feed"
# edit this to fix the deployment issue (relative path)
baseurl: /market-data-project

# Build settings
# Sass
sass:
    style: compressed
markdown: kramdown
permalink: pretty

collections:
    partners:
        output: true
