# Site settings
title: Blocksteam
description: "Cryptocurrency data feed"
# edit this to fix the deployment issue (relative path)
baseurl: 

# Build settings
# Sass
sass:
    style: compressed
markdown: kramdown
permalink: pretty
