# Site settings
title: Blockstream - Crypto Feed
siteurl: http://amrsekilly.gitlab.io
description: "Cryptocurrency data feed"
# edit this to fix the deployment issue (relative path)
baseurl: /test-blockstream

# Build settings
# Sass
sass:
    style: compressed
markdown: kramdown
permalink: pretty

plugins: [jekyll-paginate] 
paginate: 2
paginate_path: "/blog/page:num/"

collections:
    partners:
        output: true
