# Site settings
title: Blockstream
description: "Cryptocurrency data feed"
# edit this to fix the deployment issue (relative path)
baseurl: /blockStream

# Build settings
# Sass
sass:
    style: compressed
markdown: kramdown
permalink: pretty
